app.model.set({
	name:"user",
	init:function(module){
		var zone={};
		/*登录*/
		module.exports.login=function(name,key,fn){
			var result=_.findWhere(module.cache,{name:name,key:key});
			if(result){
				fn(result);
			}else{
				app.pop.on("账号或密码错误");
				fn(false);
			}
		};
		module.exports.regest=function(name,key,fn){
			if(_.findWhere(module.cache,{name:name})){
				app.pop.on("注册手机已有");
				fn(false);
			}else{/*写入*/
				var newId=app.uuid();
				module.cache[newId]={
					id:newId,
					name:name,
					key:key,
					step:["star"],
					stepDay:0,
					icon:"",
					dsc:"",
					sex:0,
					age:0,
					province:"",
					city:"",
					birthday:0,
					job:"",
					company:"",
					school:"",
					hometown:"",
					email:"",
					mine:{
						interested:"",
						music:"",
						idol:"",
						readed:"",
						heared:""
					},
					album:[],
					group:[],
					money:0,
					vip:null,
					vipDay:0,
					diy:{
						pop:null,
						redpacket:null,
						style:null,
						font:null,
						ticket:null,
						call:null,
						background:null,
						face:null,
						music:null,
						suit:null,
						pandant:null
					},
					collection:[],
					file:[],
					praise:[],
					attention:[],
					readed:[],
					share:[],
					reply:[],
					friend:{
						checked:[],
						request:[],
						response:[],
						reject:[]
					}
				};
				module.set(module,fn);
			}
		};
		/*添加好友*/
		module.exports.addFriend=function(from,to,fn){
			if(!_.contains(module.cache[to].friend.reject, from)){
				module.cache[from].friend.request.push(to);
				module.cache[to].friend.response.push(from);
				module.set(module,fn);
			}else{
				if(fn){fn(false);}
			}
		};
		/*拒绝添加好友*/
		module.exports.rejectFriend=function(from,to,fn){
			module.cache[to].friend.reject.push(from);
			module.cache[from].friend.request=_.without(module.cache[from].friend.request,to);
			module.cache[to].friend.response=_.without(module.cache[from].friend.response,from);
			module.set(module,fn);
		};
		/*确认添加好友*/
		module.exports.checkFriend=function(from,to,fn){
			module.cache[from].friend.checked.push(to);
			module.cache[to].friend.checked.push(from);
			module.cache[from].friend.request=_.without(module.cache[from].friend.request,to);
			module.cache[to].friend.response=_.without(module.cache[from].friend.response,from);
			module.set(module,fn);
		};
		/*删除好友*/
		module.exports.removeFriend=function(from,to,fn){
			module.cache[to].friend.reject.push(from);
			module.cache[from].friend.checked=_.without(module.cache[from].friend.checked,to);
			module.cache[to].friend.checked=_.without(module.cache[from].friend.checked,from);
			module.set(module,fn);
		};
		/*赞*/
		module.exports.praise=function(zid,id,fn,end){
			module.cache[id].praise.push(zid);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					zone.praise(zid,id,fn,true);	
				}
			});	
		};
		/*取消赞*/
		module.exports.cancelPraise=function(zid,id,fn,end){
			module.cache[id].praise=_.without(module.cache[id].praise,zid);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					zone.cancelPraise(zid,id,fn,true);
				}
			});
		};
		/*关注*/
		module.exports.attention=function(zid,id,fn,end){
			module.cache[id].attention.push(zid);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					zone.attention(zid,id,fn,true);
				}
			});
		};
		/*取消关注*/
		module.exports.cancelAttention=function(zid,id,fn,end){
			module.cache[id].attention=_.without(module.cache[id].attention,zid);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					zone.cancelAttention(zid,id,fn,true);
				}
			});
		};
		/*看了*/
		module.exports.readed=function(zid,id,fn,end){
			module.cache[id].readed.push(zid);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					zone.readed(zid,id,fn,true);
				}
			});
		};
		/*分享*/
		module.exports.share=function(zid,id,fn,end){
			module.cache[id].share.push(zid);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					zone.share(zid,id,fn,true);
				}
			});
		};
		/*回复*/
		module.exports.reply=function(zid,id,to,text,fn,end){
			module.cache[id].reply.push({form:id,to:to,text:text,readed:false,time:new Date().getTime(),zid:zid});
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					zone.reply(zid,id,to,text,fn,true);
				}
			});
		};
		app.model.get("zone",function(returnData){
			zone=returnData;
		});
	},
	get:function(module,callback){/*从数据源获取数据*/
		if(app.cache(module.name)){
				module.cache=app.cache(module.name);
					if(callback){/*返回*/
							callback();
						}
				}else{
				module.set(module,callback);
			}
		
	},
	set:function(module,callback){/*把数据推送到数据源*/
		app.cache(module.name,module.cache);
		if(callback){/*返回*/
			callback();
		}
	}
});