app.model.set({
	name:"zone",
	init:function(module){
		var user={};
		/*获取聊天记录*/
		module.exports.get=function(id,fn){
			var result=_.where(module.cache,{user:id});
			if(result&&result.length){
				fn(result);
			}else{
				fn(false);
			}
		};
		/*赞*/
		module.exports.praise=function(zid,id,fn,end){
			module.cache[zid].praise.push(id);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					user.praise(zid,id,fn,true);	
				}
			});
		};
		/*取消赞*/
		module.exports.cancelPraise=function(zid,id,fn,end){
			module.cache[zid].praise=_.without(module.cache[zid].praise,id);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					user.cancelPraise(zid,id,fn,true);
				}
			});
		};
		/*关注*/
		module.exports.attention=function(zid,id,fn,end){
			module.cache[zid].attention.push(id);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					user.attention(zid,id,fn,true);
				}
			});
		};
		/*取消关注*/
		module.exports.cancelAttention=function(zid,id,fn,end){
			module.cache[zid].attention=_.without(module.cache[zid].attention,id);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					user.cancelAttention(zid,id,fn,true);
				}
			});
		};
		/*看了*/
		module.exports.readed=function(zid,id,fn,end){
			module.cache[zid].readed.push(id);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					user.readed(zid,id,fn,true);
				}
			});
		};
		/*分享*/
		module.exports.share=function(zid,id,fn,end){
			module.cache[zid].share.push(id);
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					user.share(zid,id,fn,true);
				}
			});
		};
		/*回复*/
		module.exports.reply=function(zid,id,to,text,fn,end){
			module.cache[zid].reply.push({form:id,to:to,text:text,readed:false,time:new Date().getTime()});
			module.set(module,function(){
				if(end){
					if(fn){fn(true);}
				}else{
					user.reply(zid,id,to,text,fn,true);
				}
			});
		};
		/*发帖*/
		module.exports.add=function(id,title,text,pic,fn){
				var newId=app.uuid();
				module.cache[newId]={
					id:newId,
					time:new Date().getTime(),
					user:id,
					title:title,
					text:text,
					pic:pic,
					praise:[],
					attention:[],
					readed:[],
					share:[],
					reply:[]	
				};
				module.set(module,fn);
		};
		app.model.get("user",function(returnObj){
			user=returnObj;
		});
	},
	get:function(module,callback){/*从数据源获取数据*/
		if(app.cache(module.name)){
				module.cache=app.cache(module.name);
				if(callback){/*返回*/
					callback();
				}
				}else{
				module.set(module,callback);
			}
	},
	set:function(module,callback){/*把数据推送到数据源*/
		app.cache(module.name,module.cache);
		if(callback){/*返回*/
			callback();
		}
	}
});